name: okofygpt

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.x  # Adjust the Ruby version as needed

      - name: Install dependencies
        run: bundle install

      - name: Run your Ruby script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: ruby main.rb  # Adjust the script name as needed
